### ISSUE TITLE
is this new official wallet?

### ISSUE THREAD

**Issue by PSLLSP** [dev-ptera/thebananostand#127]
There was online wallet at https://vault.banano.cc/. It is not working for few days. There was no official message that it will be shutdown or replaced with something else, like https://thebananostand.com/

I am not sure about status of thebananostand.com. Is it legit? Or is it a scam to steal my secret passphrase and bananas?? Could you update this ticket with a reference to some official message or announcement that vault.banano.cc was replaced with thebananostand.com ??

This [wiki](https://banano.fandom.com/wiki/Vault) still points to vault.banano.cc

thebananostand even doesn't have dedicated page at [wiki](https://banano.fandom.com/wiki/Wallets)

**Comment by dev-ptera** [comment]
Yep you're in the right place! This is the current official web wallet for Banano.

If you check out the [Banano website](https://banano.cc/), the wallets section has been updated to remove Vault & mention TheBananoStand instead.
Also [here](https://discord.com/channels/415935345075421194/416306132651606016/1177941594339553322) is the discord announcement stating that Vault is deprecated & will be shut down 12/31/23.  

This wallet is actively being developed over time so if you have suggestions or need assistance or any way, this repo or the discord can get you the support needed.
