### ISSUE TITLE
Add an Option to Clear All Session LocalStorage Data

### ISSUE THREAD

**Issue by dev-ptera** [dev-ptera/thebananostand#21]
#### Overview

Add an option to the Settings menu (top left corner) that clears all LocalStorage information on long-press.
This should effectively clear all Wallet Information so that on page refresh, the site does not remember the user. 

This image represents a rough idea of what this new option would look like (2nd option):

<img width="743" alt="Screen Shot 2022-10-03 at 7 31 34 PM" src="https://user-images.githubusercontent.com/80925677/193704193-dadf7438-91ff-4730-b646-95d5672ff950.png">

#### Running the Project

1. Clone the Repo
2. run `yarn && yarn start` 
3. Enter the test seed: 727A5E960F6189BBF196D84A6B7715D0A78DE82AC15BBDB340540076768CDB31
4. Observe Settings icon in top-right corner

#### Additional Info

This is the file where this menu should be added:
https://github.com/dev-ptera/thebananostand/blob/master/src/app/components/account-settings/account-settings.component.ts

**Comment by koushikpuppala** [comment]
Hey Can i work on this.

**Comment by dev-ptera** [comment]
> Hey Can i work on this.
> If yes please assign this to me.

All yours 👍

**Comment by dev-ptera** [comment]
I'm self-assigning this issue now, since it's been almost 3 weeks.
